### PR TITLE
include ago by default in ui

### PR DESCRIPTION
**Pull request by kstolte**

### CODE REVIEW

**Review by aml3ed — COMMENTED** [review]
Does this make it always show "ago" - cause we probably only want that for <24 hours

**Comment by kstolte** [comment]
Good question, yes it does. But I think it does make sense.

image

currently it is displaying like this for > 24 hours. which im not thinking makes sense.
image

**Comment by kstolte** [comment]
ah yes I see your concern. by moving to moment we are going away from the date in plain text to just showing the relative date text.

I think that's ok though... maybe as a tool tip have the full date show on highlight? or do you prefer the hard date? I think I like the always relative.

**Comment by aml3ed** [comment]
Ohh gotcha - didn't know moment changed formatting - yeah sounds good!  Makes it like you're reading a sentence which is cool.  I'll add that tooltip to this branch

**Review by aml3ed — APPROVED** [review]

**Comment by kstolte** [comment]
I can't approve via gh but I approve of your change as well. thanks for getting to that so quickly.

**Pull request merged**
